apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-provider
spec:
  acme:
    server: https://acem-v02.api.letsencrypt.org/directory
    email: 'bhasaless007@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}